# Generated by Django 5.0.3 on 2024-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='domen',
            field=models.CharField(default='aaa.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(max_length=100),
        ),
    ]
