# Generated by Django 5.0.3 on 2024-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0002_campaign_domen_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='api_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='conversion_name',
            field=models.CharField(default='LEAD', max_length=100),
            preserve_default=False,
        ),
    ]
